services:
  app:
    build: .
    image: pmscan-backend:latest
    volumes:
      - app_data:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  app_data:
  postgres_data:
  redis_data: