name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker-compose -f /path/to/docker-compose.yml down
          docker-compose -f /path/to/docker-compose.yml up -d
